import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '~/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen font-TTSmalls bg-car-image-bg bg-cover bg-center bg-no-repeat">
        <main className="flex-grow bg-shadow-bg min-h-screen h-screen text-white flex items-center justify-center bg-cover bg-center bg-no-repeat ">
          <section className="h-5/6 w-4/6 bg-main-gray p-6 flex flex-col ">
            <NavBar />
            <div className="flex-grow border-2 border-main-border border-t-0 overflow-y-auto">
              {children}
            </div>
          </section>
        </main>
      </body>
    </html>
  )
}
//bg-test-bg
